"""initial schema

Revision ID: df21fab595ca
Revises: 
Create Date: 2026-07-24 00:41:30.384313
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'df21fab595ca'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('past_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('client', sa.String(length=512), nullable=True),
    sa.Column('work_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('embedding_indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_past_projects'))
    )
    op.create_index(op.f('ix_past_projects_category'), 'past_projects', ['category'], unique=False)
    op.create_index(op.f('ix_past_projects_work_value'), 'past_projects', ['work_value'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_number', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenders'))
    )
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('boq_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('item_number', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_boq_items_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boq_items'))
    )
    op.create_index(op.f('ix_boq_items_category'), 'boq_items', ['category'], unique=False)
    op.create_index(op.f('ix_boq_items_tender_id'), 'boq_items', ['tender_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_tender_documents_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_documents'))
    )
    op.create_index(op.f('ix_tender_documents_sha256'), 'tender_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_tender_documents_status'), 'tender_documents', ['status'], unique=False)
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_table('tender_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_tender_metadata_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_metadata'))
    )
    op.create_index(op.f('ix_tender_metadata_tender_id'), 'tender_metadata', ['tender_id'], unique=True)
    op.create_table('tender_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=False),
    sa.Column('after_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_tender_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_tender_reviews_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_reviews'))
    )
    op.create_index(op.f('ix_tender_reviews_reviewer_id'), 'tender_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_tender_reviews_tender_id'), 'tender_reviews', ['tender_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tender_reviews_tender_id'), table_name='tender_reviews')
    op.drop_index(op.f('ix_tender_reviews_reviewer_id'), table_name='tender_reviews')
    op.drop_table('tender_reviews')
    op.drop_index(op.f('ix_tender_metadata_tender_id'), table_name='tender_metadata')
    op.drop_table('tender_metadata')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_status'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_sha256'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_boq_items_tender_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_category'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_past_projects_work_value'), table_name='past_projects')
    op.drop_index(op.f('ix_past_projects_category'), table_name='past_projects')
    op.drop_table('past_projects')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
