"""Repository ports — persistence abstractions the application layer depends on.

Concrete SQLAlchemy implementations live in ``infrastructure.repositories``.
All list operations are paginated and return a :class:`Page`.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date, datetime
from decimal import Decimal
from typing import Protocol
from uuid import UUID

from tender_intel.domain.entities import (
    AuditLog,
    BOQItem,
    PastProject,
    RoleAssignment,
    Tender,
    TenderDocument,
    TenderMetadata,
    TenderReview,
    User,
    UserSession,
)
from tender_intel.domain.enums.document_status import DocumentStatus
from tender_intel.domain.enums.tender_status import TenderStatus
from tender_intel.domain.value_objects.pagination import Page, PageRequest


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_google_sub(self, google_sub: str) -> User | None: ...
    async def list(self, page: PageRequest) -> Page[User]: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...


class RoleAssignmentRepository(Protocol):
    async def add(self, assignment: RoleAssignment) -> RoleAssignment: ...
    async def get(self, assignment_id: UUID) -> RoleAssignment | None: ...
    async def get_by_email(self, email: str) -> RoleAssignment | None: ...
    async def list(self, page: PageRequest) -> Page[RoleAssignment]: ...
    async def update(self, assignment: RoleAssignment) -> RoleAssignment: ...
    async def delete(self, assignment_id: UUID) -> None: ...


class UserSessionRepository(Protocol):
    async def add(self, session: UserSession) -> UserSession: ...
    async def get(self, session_id: UUID) -> UserSession | None: ...
    async def get_by_token_hash(self, token_hash: str) -> UserSession | None: ...
    async def list_for_user(self, user_id: UUID) -> list[UserSession]: ...
    async def update(self, session: UserSession) -> UserSession: ...


class TenderRepository(Protocol):
    async def add(self, tender: Tender) -> Tender: ...
    async def get(self, tender_id: UUID) -> Tender | None: ...
    async def get_by_number(self, tender_number: str) -> Tender | None: ...
    async def exists_number(self, tender_number: str) -> bool: ...
    async def list(
        self,
        page: PageRequest,
        *,
        status: TenderStatus | None = None,
        search: str | None = None,
    ) -> Page[Tender]: ...
    async def update(self, tender: Tender) -> Tender: ...
    async def delete(self, tender_id: UUID) -> None: ...


class TenderDocumentRepository(Protocol):
    async def add(self, document: TenderDocument) -> TenderDocument: ...
    async def get(self, document_id: UUID) -> TenderDocument | None: ...
    async def list_for_tender(self, tender_id: UUID) -> list[TenderDocument]: ...
    async def list_by_status(self, status: DocumentStatus, limit: int) -> list[TenderDocument]: ...
    async def update(self, document: TenderDocument) -> TenderDocument: ...


class TenderMetadataRepository(Protocol):
    async def get_for_tender(self, tender_id: UUID) -> TenderMetadata | None: ...
    async def upsert(self, metadata: TenderMetadata) -> TenderMetadata: ...


class BOQItemRepository(Protocol):
    async def add_many(self, items: list[BOQItem]) -> list[BOQItem]: ...
    async def list_for_tender(self, tender_id: UUID) -> list[BOQItem]: ...
    async def delete_for_tender(self, tender_id: UUID) -> None: ...


class PastProjectRepository(Protocol):
    async def add(self, project: PastProject) -> PastProject: ...
    async def get(self, project_id: UUID) -> PastProject | None: ...
    async def get_many(self, ids: Sequence[UUID]) -> Sequence[PastProject]: ...
    async def list(self, page: PageRequest) -> Page[PastProject]: ...
    async def list_by_min_work_value(self, minimum: Decimal) -> Sequence[PastProject]: ...
    async def list_unindexed(self, limit: int) -> Sequence[PastProject]: ...
    async def update(self, project: PastProject) -> PastProject: ...
    async def delete(self, project_id: UUID) -> None: ...


class TenderReviewRepository(Protocol):
    async def add(self, review: TenderReview) -> TenderReview: ...
    async def get(self, review_id: UUID) -> TenderReview | None: ...
    async def list_for_tender(self, tender_id: UUID) -> list[TenderReview]: ...
    async def latest_verdict_at(self, tender_id: UUID) -> datetime | None: ...


class AuditLogRepository(Protocol):
    async def add(self, entry: AuditLog) -> AuditLog: ...
    async def list(
        self,
        page: PageRequest,
        *,
        actor_id: UUID | None = None,
        entity_type: str | None = None,
        action: str | None = None,
        date_from: date | None = None,
        date_to: date | None = None,
    ) -> Page[AuditLog]: ...
